import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'
import { Footer, Header ,Change} from "./Components/shared";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>MyPortfolio</title>
    <link rel="icon" href="./img/ahmed2.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta
      name="description"
      content="Web site created using create-react-app"
    />
      </head>
       <body className="container">
      <div className="row">
        <div className="col-12 col-md-4 col-lg-4">
          <Footer />
        </div>
        <div className="col-12 col-md-8 col-lg-8">
          <Header />
          {children}
        </div>
      </div>
    </body>
    </html>
  )
}
